server:
  port: 8080
swagger:
  enable: true
  basePackage: com.zxb.admin.controller
# spring连接数据库驱动
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://119.23.219.141:3306/template?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://localhost:3306/zxb_template?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # Hikari will use the above plus the following to setup connection pooling
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #      ddl-auto: update none
      use-new-id-generator-mappings: true
  jackson:
    serialization:
      indent_output: false